// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Klp9ikNqQ6uR7gcl940ZV9xxjTl30Bg',
    appId: '1:398843377397:ios:a762f3c57ddc43251137bc',
    messagingSenderId: '398843377397',
    projectId: 'group-3-8065d',
    databaseURL: 'https://group-3-8065d-default-rtdb.firebaseio.com',
    storageBucket: 'group-3-8065d.firebasestorage.app',
    iosBundleId: 'com.smartfan.example',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgZWz5EpR5vaajIidhgI61jgQf5tkWgvs',
    appId: '1:398843377397:web:1878686f0b2395e61137bc',
    messagingSenderId: '398843377397',
    projectId: 'group-3-8065d',
    authDomain: 'group-3-8065d.firebaseapp.com',
    databaseURL: 'https://group-3-8065d-default-rtdb.firebaseio.com',
    storageBucket: 'group-3-8065d.firebasestorage.app',
  );

}