name: Build_TrollStore_IPA

on:
  push:
    branches: [ main ]

# Giải quyết cảnh báo Node.js 20 bằng cách ép sử dụng Node 24
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      # Sử dụng v4 để tương thích tốt nhất với môi trường mới
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get Dependencies
        run: flutter pub get

      - name: Build iOS App (No Sign)
        # Build bản release không cần chứng chỉ Apple dành cho TrollStore
        run: flutter build ios --release --no-codesign

      - name: Create IPA Structure
        run: |
          mkdir Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -vr SmartFan.ipa Payload/

      - name: Upload IPA Artifact
        # Sử dụng v4 để đảm bảo tốc độ và không bị lỗi thời
        uses: actions/upload-artifact@v4
        with:
          name: Smart-Fan-Install-File
          path: SmartFan.ipa